<a href="https://colab.research.google.com/github/igarashimassaki/Alg_e_LP_2026.2/blob/main/AlgLP_07_AD2_3_Exemplo_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center">

# **O FORMATO JSON**

</div>

<div align="justify">

### **JSON (JavaScript Object Notation) é o formato mais popular do mundo para enviar e organizar informações na internet. Pense nele como a versão digital de uma ficha cadastral preenchida: ele serve para que computadores diferentes (como o seu celular e o servidor de um aplicativo) conversem e entendam os mesmos dados de forma rápida.**
### **A grande vantagem do JSON é que ele foi feito para ser lido facilmente tanto por máquinas quanto por seres humanos.**

###**💡 A analogia do formulário**

### **Para entender na prática, imagine que você está preenchendo os dados de um livro em um sistema.**
### **Em vez de escrever um texto corrido, o JSON organiza as informações em pares de "pergunta e resposta" (que na programação chamamos de chave e valor), sempre usando aspas e separados por dois-pontos.**
### **Veja como fica um exemplo de JSON:**

</div>

<div align="justify">

### **Em lingugem de programação, o conceito de chave-valor (key-value) funciona como uma etiqueta presa a um objeto. A chave é o identificador único (a etiqueta) e o valor é o dado guardado (o objeto).No exemplo a seguir, além do nome, elementos comuns como id e email também funcionam perfeitamente como chaves, pois servem para identificar informações específicas sobre o usuário.**

# **EXEMPLO DE CÓDIGO 01:**
# Criando um par chave-valor para um usuário
</div>

In [ ]:
usuario = {
    "id": 1025,
    "nome": "Maria",
    "email": "maria@email.com"
}
# Acessando o valor através da chave
print(usuario["nome"])
# Saída: Maria

Maria

<div align="justify">
### **Estrutura Completa de Chaves e Valores**
### **Olhando novamente para o nosso código, cada uma das chaves cumpre um papel de identificação para o seu respectivo valor:**
• Chave **id:** É o identificador numérico único do usuário.

	• Seu Valor (1025): Um número inteiro. Ele funciona como o "RG" ou "CPF" no sistema, garantindo que este usuário nunca seja confundido com outro, mesmo que tenham o mesmo nome.

• Chave **nome:** É a etiqueta para o nome da pessoa.

	• Seu Valor ("Maria"): Um texto (string) com o nome próprio do usuário.


• Chave **email:** É a etiqueta para o endereço de contato eletrônico.

	• Seu Valor ("maria@email.com"): Um texto (string) contendo o e-mail. Na prática, o e-mail também costuma ser único no sistema, sendo ótimo para buscas rápidas.
  

### **Representação Visual do Armazenamento**

### **Por trás dos panos, o computador organiza esses dados em uma tabela de associação direta:**

|Chave (Key) | Valor (Value) | Tipo do Dado
| :--- | :---: | ---: |
| id | 1025	| Número Inteiro (Integer) |
| nome | "Maria" | Texto (String) |
| email	| "maria@email.com"	| Texto (String) |

### **Para recuperar qualquer uma dessas informações no código, você só precisa chamar a chave desejada**

</div>

# **EXEMPLO DE CÓDIGO 02:**
# Criando um par chave-valor

In [ ]:
import pandas as pd
from IPython.display import display #Usarei esta LIB IPython.display para conseguir executar Função display no Vscode

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

display(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

'''
<div align="justify">

## **Agora Vamos entender este código a seguir por meio de uma analogia simples do dia a dia: organizar uma receita de cozinha. Imagine que você tem uma folha de papel com anotações de dados importantes (como calorias e batimentos cardíacos), mas essas anotações vieram com alguns rabiscos extras e você quer colocá-las em uma planilha bonita do Excel para conseguir ler com facilidade. É exatamente isso que seu código faz!**
#**Vamos ao passo a passo simplificado:**

</div>


# **1. Chamando os ajudantes especialistas (As Bibliotecas)**

import pandas as pd

import json

from IPython.display import display


**pandas:** Pense no Pandas como o seu "Excel dentro do Python". Ele é o especialista em criar e manipular tabelas de forma mágica.

**json:** O JSON é um formato muito popular na internet para guardar dados (como se fosse um bloco de notas organizado com chaves e valores). Esse ajudante sabe ler esse formato.

**display:** É o ajudante responsável por mostrar a tabela na sua tela de um jeito bonito e formatado.


#**2. Abrindo a gaveta e pegando o papel (Leitura do Arquivo)**

with open('BaseDadosJSON.json', 'r', encoding='utf-8') as f:
    conteudo = f.read().strip()

Aqui o computador está abrindo o arquivo chamado BaseDadosJSON.json (como quem abre uma gaveta para ler uma carta).

O **read().strip()** lê todo o texto da carta e "limpa" os espaços vazios e quebras de linha inúteis no início e no final.


#**3. Limpando a "sujeira" do papel (Tratamento do Texto)**

if conteudo.startswith('data = '):
    conteudo_json = conteudo.replace('data = ', '', 1)
else:
    conteudo_json = conteudo


O computador precisa de um formato JSON limpo. Porém, o texto vinha escrito com data = { ... } na primeira linha. Para o computador, esse data = é como um rabisco desnecessário na folha.

O código faz uma pergunta simples: "O texto começa com 'data = '?". Se sim, ele apaga esse trecho (replace) e guarda apenas o que interessa (o texto limpo do JSON).


#**4. Traduzindo o texto e criando a planilha (Conversão e Visualização)**

dados = json.loads(conteudo_json)
df = pd.DataFrame(dados)
display(df)

**json.loads:** Traduz o texto limpo que estava no arquivo e o transforma em uma estrutura que o Python entende nativamente (um dicionário).

**pd.DataFrame:** Pega essa estrutura traduzida e monta uma tabela oficial (com linhas e colunas organizadas), chamada tecnicamente de DataFrame.

**display(df):** Finalmente, desenha essa planilha na sua tela para que você possa visualizá-la perfeitamente.
Pronto! Com esses passos, um arquivo de texto meio bagunçado se transformou em uma tabela organizada e pronta para análise.

'''

In [ ]:
import pandas as pd
import json
from IPython.display import display

# Lendo o arquivo como texto
with open('BaseDadosJSON.json', 'r', encoding='utf-8') as f:
    conteudo = f.read().strip()

# Remove o prefixo 'data = ' se ele existir para tornar o JSON válido
if conteudo.startswith('data = '):
    conteudo_json = conteudo.replace('data = ', '', 1)
else:
    conteudo_json = conteudo

# Converte a string tratada em um dicionário e carrega no DataFrame
dados = json.loads(conteudo_json)
df = pd.DataFrame(dados)

display(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [ ]:
import json
import pandas as pd

# 1. Solicita os novos valores ao usuário
duration = int(input("Digite o valor para 'Duration': "))
pulse = int(input("Digite o valor para 'Pulse': "))
maxpulse = int(input("Digite o valor para 'Maxpulse': "))
calories = int(input("Digite o valor para 'Calories': "))

# 2. Abre o arquivo existente e carrega os dados atuais
with open('BaseDadosJSON.json', 'r', encoding='utf-8') as f:
    conteudo = f.read().strip()

if conteudo.startswith('data = '):
    conteudo_json = conteudo.replace('data = ', '', 1)
else:
    conteudo_json = conteudo

dados = json.loads(conteudo_json)

# 3. Descobre o próximo índice numérico (chave)
proximo_indice = str(len(dados['Duration']))

# 4. Insere os novos valores no dicionário
dados['Duration'][proximo_indice] = duration
dados['Pulse'][proximo_indice] = pulse
dados['Maxpulse'][proximo_indice] = maxpulse
dados['Calories'][proximo_indice] = calories

# 5. Salva os dados atualizados de volta no arquivo mantendo o formato original 'data = ...'
with open('BaseDadosJSON.json', 'w', encoding='utf-8') as f:
    f.write('data = ' + json.dumps(dados, indent=2))

print("\nValores salvos com sucesso no arquivo 'BaseDadosJSON.json'!")

# Mostra a tabela atualizada
df_atualizado = pd.DataFrame(dados)
display(df_atualizado)

Digite o valor para 'Duration': 90
Digite o valor para 'Pulse': 120
Digite o valor para 'Maxpulse': 150
Digite o valor para 'Calories': 350

Valores salvos com sucesso no arquivo 'BaseDadosJSON.json'!

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300
6        90    120       150       350